@file:Suppress("unused", "PropertyName", "SpellCheckingInspection")
@file:JsModule("react-icons/fa")
@file:JsNonModule
package react_icons.fa

import react_icons.lib.IconType

external val Fa500Px: IconType
external val FaAccessibleIcon: IconType
external val FaAccusoft: IconType
external val FaAcquisitionsIncorporated: IconType
external val FaAdn: IconType
external val FaAdversal: IconType
external val FaAffiliatetheme: IconType
external val FaAirbnb: IconType
external val FaAlgolia: IconType
external val FaAlipay: IconType
external val FaAmazonPay: IconType
external val FaAmazon: IconType
external val FaAmilia: IconType
external val FaAndroid: IconType
external val FaAngellist: IconType
external val FaAngrycreative: IconType
external val FaAngular: IconType
external val FaAppStoreIos: IconType
external val FaAppStore: IconType
external val FaApper: IconType
external val FaApplePay: IconType
external val FaApple: IconType
external val FaArtstation: IconType
external val FaAsymmetrik: IconType
external val FaAtlassian: IconType
external val FaAudible: IconType
external val FaAutoprefixer: IconType
external val FaAvianex: IconType
external val FaAviato: IconType
external val FaAws: IconType
external val FaBandcamp: IconType
external val FaBattleNet: IconType
external val FaBehanceSquare: IconType
external val FaBehance: IconType
external val FaBimobject: IconType
external val FaBitbucket: IconType
external val FaBitcoin: IconType
external val FaBity: IconType
external val FaBlackTie: IconType
external val FaBlackberry: IconType
external val FaBloggerB: IconType
external val FaBlogger: IconType
external val FaBluetoothB: IconType
external val FaBluetooth: IconType
external val FaBootstrap: IconType
external val FaBtc: IconType
external val FaBuffer: IconType
external val FaBuromobelexperte: IconType
external val FaBuyNLarge: IconType
external val FaBuysellads: IconType
external val FaCanadianMapleLeaf: IconType
external val FaCcAmazonPay: IconType
external val FaCcAmex: IconType
external val FaCcApplePay: IconType
external val FaCcDinersClub: IconType
external val FaCcDiscover: IconType
external val FaCcJcb: IconType
external val FaCcMastercard: IconType
external val FaCcPaypal: IconType
external val FaCcStripe: IconType
external val FaCcVisa: IconType
external val FaCentercode: IconType
external val FaCentos: IconType
external val FaChrome: IconType
external val FaChromecast: IconType
external val FaCloudflare: IconType
external val FaCloudscale: IconType
external val FaCloudsmith: IconType
external val FaCloudversify: IconType
external val FaCodepen: IconType
external val FaCodiepie: IconType
external val FaConfluence: IconType
external val FaConnectdevelop: IconType
external val FaContao: IconType
external val FaCottonBureau: IconType
external val FaCpanel: IconType
external val FaCreativeCommonsBy: IconType
external val FaCreativeCommonsNcEu: IconType
external val FaCreativeCommonsNcJp: IconType
external val FaCreativeCommonsNc: IconType
external val FaCreativeCommonsNd: IconType
external val FaCreativeCommonsPdAlt: IconType
external val FaCreativeCommonsPd: IconType
external val FaCreativeCommonsRemix: IconType
external val FaCreativeCommonsSa: IconType
external val FaCreativeCommonsSamplingPlus: IconType
external val FaCreativeCommonsSampling: IconType
external val FaCreativeCommonsShare: IconType
external val FaCreativeCommonsZero: IconType
external val FaCreativeCommons: IconType
external val FaCriticalRole: IconType
external val FaCss3Alt: IconType
external val FaCss3: IconType
external val FaCuttlefish: IconType
external val FaDAndDBeyond: IconType
external val FaDAndD: IconType
external val FaDailymotion: IconType
external val FaDashcube: IconType
external val FaDeezer: IconType
external val FaDelicious: IconType
external val FaDeploydog: IconType
external val FaDeskpro: IconType
external val FaDev: IconType
external val FaDeviantart: IconType
external val FaDhl: IconType
external val FaDiaspora: IconType
external val FaDigg: IconType
external val FaDigitalOcean: IconType
external val FaDiscord: IconType
external val FaDiscourse: IconType
external val FaDochub: IconType
external val FaDocker: IconType
external val FaDraft2Digital: IconType
external val FaDribbbleSquare: IconType
external val FaDribbble: IconType
external val FaDropbox: IconType
external val FaDrupal: IconType
external val FaDyalog: IconType
external val FaEarlybirds: IconType
external val FaEbay: IconType
external val FaEdgeLegacy: IconType
external val FaEdge: IconType
external val FaElementor: IconType
external val FaEllo: IconType
external val FaEmber: IconType
external val FaEmpire: IconType
external val FaEnvira: IconType
external val FaErlang: IconType
external val FaEthereum: IconType
external val FaEtsy: IconType
external val FaEvernote: IconType
external val FaExpeditedssl: IconType
external val FaFacebookF: IconType
external val FaFacebookMessenger: IconType
external val FaFacebookSquare: IconType
external val FaFacebook: IconType
external val FaFantasyFlightGames: IconType
external val FaFedex: IconType
external val FaFedora: IconType
external val FaFigma: IconType
external val FaFirefoxBrowser: IconType
external val FaFirefox: IconType
external val FaFirstOrderAlt: IconType
external val FaFirstOrder: IconType
external val FaFirstdraft: IconType
external val FaFlickr: IconType
external val FaFlipboard: IconType
external val FaFly: IconType
external val FaFontAwesomeAlt: IconType
external val FaFontAwesomeFlag: IconType
external val FaFontAwesomeLogoFull: IconType
external val FaFontAwesome: IconType
external val FaFonticonsFi: IconType
external val FaFonticons: IconType
external val FaFortAwesomeAlt: IconType
external val FaFortAwesome: IconType
external val FaForumbee: IconType
external val FaFoursquare: IconType
external val FaFreeCodeCamp: IconType
external val FaFreebsd: IconType
external val FaFulcrum: IconType
external val FaGalacticRepublic: IconType
external val FaGalacticSenate: IconType
external val FaGetPocket: IconType
external val FaGgCircle: IconType
external val FaGg: IconType
external val FaGitAlt: IconType
external val FaGitSquare: IconType
external val FaGit: IconType
external val FaGithubAlt: IconType
external val FaGithubSquare: IconType
external val FaGithub: IconType
external val FaGitkraken: IconType
external val FaGitlab: IconType
external val FaGitter: IconType
external val FaGlideG: IconType
external val FaGlide: IconType
external val FaGofore: IconType
external val FaGoodreadsG: IconType
external val FaGoodreads: IconType
external val FaGoogleDrive: IconType
external val FaGooglePay: IconType
external val FaGooglePlay: IconType
external val FaGooglePlusG: IconType
external val FaGooglePlusSquare: IconType
external val FaGooglePlus: IconType
external val FaGoogleWallet: IconType
external val FaGoogle: IconType
external val FaGratipay: IconType
external val FaGrav: IconType
external val FaGripfire: IconType
external val FaGrunt: IconType
external val FaGuilded: IconType
external val FaGulp: IconType
external val FaHackerNewsSquare: IconType
external val FaHackerNews: IconType
external val FaHackerrank: IconType
external val FaHips: IconType
external val FaHireAHelper: IconType
external val FaHive: IconType
external val FaHooli: IconType
external val FaHornbill: IconType
external val FaHotjar: IconType
external val FaHouzz: IconType
external val FaHtml5: IconType
external val FaHubspot: IconType
external val FaIdeal: IconType
external val FaImdb: IconType
external val FaInnosoft: IconType
external val FaInstagramSquare: IconType
external val FaInstagram: IconType
external val FaInstalod: IconType
external val FaIntercom: IconType
external val FaInternetExplorer: IconType
external val FaInvision: IconType
external val FaIoxhost: IconType
external val FaItchIo: IconType
external val FaItunesNote: IconType
external val FaItunes: IconType
external val FaJava: IconType
external val FaJediOrder: IconType
external val FaJenkins: IconType
external val FaJira: IconType
external val FaJoget: IconType
external val FaJoomla: IconType
external val FaJsSquare: IconType
external val FaJs: IconType
external val FaJsfiddle: IconType
external val FaKaggle: IconType
external val FaKeybase: IconType
external val FaKeycdn: IconType
external val FaKickstarterK: IconType
external val FaKickstarter: IconType
external val FaKorvue: IconType
external val FaLaravel: IconType
external val FaLastfmSquare: IconType
external val FaLastfm: IconType
external val FaLeanpub: IconType
external val FaLess: IconType
external val FaLine: IconType
external val FaLinkedinIn: IconType
external val FaLinkedin: IconType
external val FaLinode: IconType
external val FaLinux: IconType
external val FaLyft: IconType
external val FaMagento: IconType
external val FaMailchimp: IconType
external val FaMandalorian: IconType
external val FaMarkdown: IconType
external val FaMastodon: IconType
external val FaMaxcdn: IconType
external val FaMdb: IconType
external val FaMedapps: IconType
external val FaMediumM: IconType
external val FaMedium: IconType
external val FaMedrt: IconType
external val FaMeetup: IconType
external val FaMegaport: IconType
external val FaMendeley: IconType
external val FaMicroblog: IconType
external val FaMicrosoft: IconType
external val FaMix: IconType
external val FaMixcloud: IconType
external val FaMixer: IconType
external val FaMizuni: IconType
external val FaModx: IconType
external val FaMonero: IconType
external val FaNapster: IconType
external val FaNeos: IconType
external val FaNimblr: IconType
external val FaNodeJs: IconType
external val FaNode: IconType
external val FaNpm: IconType
external val FaNs8: IconType
external val FaNutritionix: IconType
external val FaOctopusDeploy: IconType
external val FaOdnoklassnikiSquare: IconType
external val FaOdnoklassniki: IconType
external val FaOldRepublic: IconType
external val FaOpencart: IconType
external val FaOpenid: IconType
external val FaOpera: IconType
external val FaOptinMonster: IconType
external val FaOrcid: IconType
external val FaOsi: IconType
external val FaPage4: IconType
external val FaPagelines: IconType
external val FaPalfed: IconType
external val FaPatreon: IconType
external val FaPaypal: IconType
external val FaPennyArcade: IconType
external val FaPerbyte: IconType
external val FaPeriscope: IconType
external val FaPhabricator: IconType
external val FaPhoenixFramework: IconType
external val FaPhoenixSquadron: IconType
external val FaPhp: IconType
external val FaPiedPiperAlt: IconType
external val FaPiedPiperHat: IconType
external val FaPiedPiperPp: IconType
external val FaPiedPiperSquare: IconType
external val FaPiedPiper: IconType
external val FaPinterestP: IconType
external val FaPinterestSquare: IconType
external val FaPinterest: IconType
external val FaPlaystation: IconType
external val FaProductHunt: IconType
external val FaPushed: IconType
external val FaPython: IconType
external val FaQq: IconType
external val FaQuinscape: IconType
external val FaQuora: IconType
external val FaRProject: IconType
external val FaRaspberryPi: IconType
external val FaRavelry: IconType
external val FaReact: IconType
external val FaReacteurope: IconType
external val FaReadme: IconType
external val FaRebel: IconType
external val FaRedRiver: IconType
external val FaRedditAlien: IconType
external val FaRedditSquare: IconType
external val FaReddit: IconType
external val FaRedhat: IconType
external val FaRenren: IconType
external val FaReplyd: IconType
external val FaResearchgate: IconType
external val FaResolving: IconType
external val FaRev: IconType
external val FaRocketchat: IconType
external val FaRockrms: IconType
external val FaRust: IconType
external val FaSafari: IconType
external val FaSalesforce: IconType
external val FaSass: IconType
external val FaSchlix: IconType
external val FaScribd: IconType
external val FaSearchengin: IconType
external val FaSellcast: IconType
external val FaSellsy: IconType
external val FaServicestack: IconType
external val FaShirtsinbulk: IconType
external val FaShopify: IconType
external val FaShopware: IconType
external val FaSimplybuilt: IconType
external val FaSistrix: IconType
external val FaSith: IconType
external val FaSketch: IconType
external val FaSkyatlas: IconType
external val FaSkype: IconType
external val FaSlackHash: IconType
external val FaSlack: IconType
external val FaSlideshare: IconType
external val FaSnapchatGhost: IconType
external val FaSnapchatSquare: IconType
external val FaSnapchat: IconType
external val FaSoundcloud: IconType
external val FaSourcetree: IconType
external val FaSpeakap: IconType
external val FaSpeakerDeck: IconType
external val FaSpotify: IconType
external val FaSquarespace: IconType
external val FaStackExchange: IconType
external val FaStackOverflow: IconType
external val FaStackpath: IconType
external val FaStaylinked: IconType
external val FaSteamSquare: IconType
external val FaSteamSymbol: IconType
external val FaSteam: IconType
external val FaStickerMule: IconType
external val FaStrava: IconType
external val FaStripeS: IconType
external val FaStripe: IconType
external val FaStudiovinari: IconType
external val FaStumbleuponCircle: IconType
external val FaStumbleupon: IconType
external val FaSuperpowers: IconType
external val FaSupple: IconType
external val FaSuse: IconType
external val FaSwift: IconType
external val FaSymfony: IconType
external val FaTeamspeak: IconType
external val FaTelegramPlane: IconType
external val FaTelegram: IconType
external val FaTencentWeibo: IconType
external val FaTheRedYeti: IconType
external val FaThemeco: IconType
external val FaThemeisle: IconType
external val FaThinkPeaks: IconType
external val FaTiktok: IconType
external val FaTradeFederation: IconType
external val FaTrello: IconType
external val FaTripadvisor: IconType
external val FaTumblrSquare: IconType
external val FaTumblr: IconType
external val FaTwitch: IconType
external val FaTwitterSquare: IconType
external val FaTwitter: IconType
external val FaTypo3: IconType
external val FaUber: IconType
external val FaUbuntu: IconType
external val FaUikit: IconType
external val FaUmbraco: IconType
external val FaUncharted: IconType
external val FaUniregistry: IconType
external val FaUnity: IconType
external val FaUnsplash: IconType
external val FaUntappd: IconType
external val FaUps: IconType
external val FaUsb: IconType
external val FaUsps: IconType
external val FaUssunnah: IconType
external val FaVaadin: IconType
external val FaViacoin: IconType
external val FaViadeoSquare: IconType
external val FaViadeo: IconType
external val FaViber: IconType
external val FaVimeoSquare: IconType
external val FaVimeoV: IconType
external val FaVimeo: IconType
external val FaVine: IconType
external val FaVk: IconType
external val FaVnv: IconType
external val FaVuejs: IconType
external val FaWatchmanMonitoring: IconType
external val FaWaze: IconType
external val FaWeebly: IconType
external val FaWeibo: IconType
external val FaWeixin: IconType
external val FaWhatsappSquare: IconType
external val FaWhatsapp: IconType
external val FaWhmcs: IconType
external val FaWikipediaW: IconType
external val FaWindows: IconType
external val FaWix: IconType
external val FaWizardsOfTheCoast: IconType
external val FaWodu: IconType
external val FaWolfPackBattalion: IconType
external val FaWordpressSimple: IconType
external val FaWordpress: IconType
external val FaWpbeginner: IconType
external val FaWpexplorer: IconType
external val FaWpforms: IconType
external val FaWpressr: IconType
external val FaXbox: IconType
external val FaXingSquare: IconType
external val FaXing: IconType
external val FaYCombinator: IconType
external val FaYahoo: IconType
external val FaYammer: IconType
external val FaYandexInternational: IconType
external val FaYandex: IconType
external val FaYarn: IconType
external val FaYelp: IconType
external val FaYoast: IconType
external val FaYoutubeSquare: IconType
external val FaYoutube: IconType
external val FaZhihu: IconType
external val FaAd: IconType
external val FaAddressBook: IconType
external val FaAddressCard: IconType
external val FaAdjust: IconType
external val FaAirFreshener: IconType
external val FaAlignCenter: IconType
external val FaAlignJustify: IconType
external val FaAlignLeft: IconType
external val FaAlignRight: IconType
external val FaAllergies: IconType
external val FaAmbulance: IconType
external val FaAmericanSignLanguageInterpreting: IconType
external val FaAnchor: IconType
external val FaAngleDoubleDown: IconType
external val FaAngleDoubleLeft: IconType
external val FaAngleDoubleRight: IconType
external val FaAngleDoubleUp: IconType
external val FaAngleDown: IconType
external val FaAngleLeft: IconType
external val FaAngleRight: IconType
external val FaAngleUp: IconType
external val FaAngry: IconType
external val FaAnkh: IconType
external val FaAppleAlt: IconType
external val FaArchive: IconType
external val FaArchway: IconType
external val FaArrowAltCircleDown: IconType
external val FaArrowAltCircleLeft: IconType
external val FaArrowAltCircleRight: IconType
external val FaArrowAltCircleUp: IconType
external val FaArrowCircleDown: IconType
external val FaArrowCircleLeft: IconType
external val FaArrowCircleRight: IconType
external val FaArrowCircleUp: IconType
external val FaArrowDown: IconType
external val FaArrowLeft: IconType
external val FaArrowRight: IconType
external val FaArrowUp: IconType
external val FaArrowsAltH: IconType
external val FaArrowsAltV: IconType
external val FaArrowsAlt: IconType
external val FaAssistiveListeningSystems: IconType
external val FaAsterisk: IconType
external val FaAt: IconType
external val FaAtlas: IconType
external val FaAtom: IconType
external val FaAudioDescription: IconType
external val FaAward: IconType
external val FaBabyCarriage: IconType
external val FaBaby: IconType
external val FaBackspace: IconType
external val FaBackward: IconType
external val FaBacon: IconType
external val FaBacteria: IconType
external val FaBacterium: IconType
external val FaBahai: IconType
external val FaBalanceScaleLeft: IconType
external val FaBalanceScaleRight: IconType
external val FaBalanceScale: IconType
external val FaBan: IconType
external val FaBandAid: IconType
external val FaBarcode: IconType
external val FaBars: IconType
external val FaBaseballBall: IconType
external val FaBasketballBall: IconType
external val FaBath: IconType
external val FaBatteryEmpty: IconType
external val FaBatteryFull: IconType
external val FaBatteryHalf: IconType
external val FaBatteryQuarter: IconType
external val FaBatteryThreeQuarters: IconType
external val FaBed: IconType
external val FaBeer: IconType
external val FaBellSlash: IconType
external val FaBell: IconType
external val FaBezierCurve: IconType
external val FaBible: IconType
external val FaBicycle: IconType
external val FaBiking: IconType
external val FaBinoculars: IconType
external val FaBiohazard: IconType
external val FaBirthdayCake: IconType
external val FaBlenderPhone: IconType
external val FaBlender: IconType
external val FaBlind: IconType
external val FaBlog: IconType
external val FaBold: IconType
external val FaBolt: IconType
external val FaBomb: IconType
external val FaBone: IconType
external val FaBong: IconType
external val FaBookDead: IconType
external val FaBookMedical: IconType
external val FaBookOpen: IconType
external val FaBookReader: IconType
external val FaBook: IconType
external val FaBookmark: IconType
external val FaBorderAll: IconType
external val FaBorderNone: IconType
external val FaBorderStyle: IconType
external val FaBowlingBall: IconType
external val FaBoxOpen: IconType
external val FaBoxTissue: IconType
external val FaBox: IconType
external val FaBoxes: IconType
external val FaBraille: IconType
external val FaBrain: IconType
external val FaBreadSlice: IconType
external val FaBriefcaseMedical: IconType
external val FaBriefcase: IconType
external val FaBroadcastTower: IconType
external val FaBroom: IconType
external val FaBrush: IconType
external val FaBug: IconType
external val FaBuilding: IconType
external val FaBullhorn: IconType
external val FaBullseye: IconType
external val FaBurn: IconType
external val FaBusAlt: IconType
external val FaBus: IconType
external val FaBusinessTime: IconType
external val FaCalculator: IconType
external val FaCalendarAlt: IconType
external val FaCalendarCheck: IconType
external val FaCalendarDay: IconType
external val FaCalendarMinus: IconType
external val FaCalendarPlus: IconType
external val FaCalendarTimes: IconType
external val FaCalendarWeek: IconType
external val FaCalendar: IconType
external val FaCameraRetro: IconType
external val FaCamera: IconType
external val FaCampground: IconType
external val FaCandyCane: IconType
external val FaCannabis: IconType
external val FaCapsules: IconType
external val FaCarAlt: IconType
external val FaCarBattery: IconType
external val FaCarCrash: IconType
external val FaCarSide: IconType
external val FaCar: IconType
external val FaCaravan: IconType
external val FaCaretDown: IconType
external val FaCaretLeft: IconType
external val FaCaretRight: IconType
external val FaCaretSquareDown: IconType
external val FaCaretSquareLeft: IconType
external val FaCaretSquareRight: IconType
external val FaCaretSquareUp: IconType
external val FaCaretUp: IconType
external val FaCarrot: IconType
external val FaCartArrowDown: IconType
external val FaCartPlus: IconType
external val FaCashRegister: IconType
external val FaCat: IconType
external val FaCertificate: IconType
external val FaChair: IconType
external val FaChalkboardTeacher: IconType
external val FaChalkboard: IconType
external val FaChargingStation: IconType
external val FaChartArea: IconType
external val FaChartBar: IconType
external val FaChartLine: IconType
external val FaChartPie: IconType
external val FaCheckCircle: IconType
external val FaCheckDouble: IconType
external val FaCheckSquare: IconType
external val FaCheck: IconType
external val FaCheese: IconType
external val FaChessBishop: IconType
external val FaChessBoard: IconType
external val FaChessKing: IconType
external val FaChessKnight: IconType
external val FaChessPawn: IconType
external val FaChessQueen: IconType
external val FaChessRook: IconType
external val FaChess: IconType
external val FaChevronCircleDown: IconType
external val FaChevronCircleLeft: IconType
external val FaChevronCircleRight: IconType
external val FaChevronCircleUp: IconType
external val FaChevronDown: IconType
external val FaChevronLeft: IconType
external val FaChevronRight: IconType
external val FaChevronUp: IconType
external val FaChild: IconType
external val FaChurch: IconType
external val FaCircleNotch: IconType
external val FaCircle: IconType
external val FaCity: IconType
external val FaClinicMedical: IconType
external val FaClipboardCheck: IconType
external val FaClipboardList: IconType
external val FaClipboard: IconType
external val FaClock: IconType
external val FaClone: IconType
external val FaClosedCaptioning: IconType
external val FaCloudDownloadAlt: IconType
external val FaCloudMeatball: IconType
external val FaCloudMoonRain: IconType
external val FaCloudMoon: IconType
external val FaCloudRain: IconType
external val FaCloudShowersHeavy: IconType
external val FaCloudSunRain: IconType
external val FaCloudSun: IconType
external val FaCloudUploadAlt: IconType
external val FaCloud: IconType
external val FaCocktail: IconType
external val FaCodeBranch: IconType
external val FaCode: IconType
external val FaCoffee: IconType
external val FaCog: IconType
external val FaCogs: IconType
external val FaCoins: IconType
external val FaColumns: IconType
external val FaCommentAlt: IconType
external val FaCommentDollar: IconType
external val FaCommentDots: IconType
external val FaCommentMedical: IconType
external val FaCommentSlash: IconType
external val FaComment: IconType
external val FaCommentsDollar: IconType
external val FaComments: IconType
external val FaCompactDisc: IconType
external val FaCompass: IconType
external val FaCompressAlt: IconType
external val FaCompressArrowsAlt: IconType
external val FaCompress: IconType
external val FaConciergeBell: IconType
external val FaCookieBite: IconType
external val FaCookie: IconType
external val FaCopy: IconType
external val FaCopyright: IconType
external val FaCouch: IconType
external val FaCreditCard: IconType
external val FaCropAlt: IconType
external val FaCrop: IconType
external val FaCross: IconType
external val FaCrosshairs: IconType
external val FaCrow: IconType
external val FaCrown: IconType
external val FaCrutch: IconType
external val FaCube: IconType
external val FaCubes: IconType
external val FaCut: IconType
external val FaDatabase: IconType
external val FaDeaf: IconType
external val FaDemocrat: IconType
external val FaDesktop: IconType
external val FaDharmachakra: IconType
external val FaDiagnoses: IconType
external val FaDiceD20: IconType
external val FaDiceD6: IconType
external val FaDiceFive: IconType
external val FaDiceFour: IconType
external val FaDiceOne: IconType
external val FaDiceSix: IconType
external val FaDiceThree: IconType
external val FaDiceTwo: IconType
external val FaDice: IconType
external val FaDigitalTachograph: IconType
external val FaDirections: IconType
external val FaDisease: IconType
external val FaDivide: IconType
external val FaDizzy: IconType
external val FaDna: IconType
external val FaDog: IconType
external val FaDollarSign: IconType
external val FaDollyFlatbed: IconType
external val FaDolly: IconType
external val FaDonate: IconType
external val FaDoorClosed: IconType
external val FaDoorOpen: IconType
external val FaDotCircle: IconType
external val FaDove: IconType
external val FaDownload: IconType
external val FaDraftingCompass: IconType
external val FaDragon: IconType
external val FaDrawPolygon: IconType
external val FaDrumSteelpan: IconType
external val FaDrum: IconType
external val FaDrumstickBite: IconType
external val FaDumbbell: IconType
external val FaDumpsterFire: IconType
external val FaDumpster: IconType
external val FaDungeon: IconType
external val FaEdit: IconType
external val FaEgg: IconType
external val FaEject: IconType
external val FaEllipsisH: IconType
external val FaEllipsisV: IconType
external val FaEnvelopeOpenText: IconType
external val FaEnvelopeOpen: IconType
external val FaEnvelopeSquare: IconType
external val FaEnvelope: IconType
external val FaEquals: IconType
external val FaEraser: IconType
external val FaEthernet: IconType
external val FaEuroSign: IconType
external val FaExchangeAlt: IconType
external val FaExclamationCircle: IconType
external val FaExclamationTriangle: IconType
external val FaExclamation: IconType
external val FaExpandAlt: IconType
external val FaExpandArrowsAlt: IconType
external val FaExpand: IconType
external val FaExternalLinkAlt: IconType
external val FaExternalLinkSquareAlt: IconType
external val FaEyeDropper: IconType
external val FaEyeSlash: IconType
external val FaEye: IconType
external val FaFan: IconType
external val FaFastBackward: IconType
external val FaFastForward: IconType
external val FaFaucet: IconType
external val FaFax: IconType
external val FaFeatherAlt: IconType
external val FaFeather: IconType
external val FaFemale: IconType
external val FaFighterJet: IconType
external val FaFileAlt: IconType
external val FaFileArchive: IconType
external val FaFileAudio: IconType
external val FaFileCode: IconType
external val FaFileContract: IconType
external val FaFileCsv: IconType
external val FaFileDownload: IconType
external val FaFileExcel: IconType
external val FaFileExport: IconType
external val FaFileImage: IconType
external val FaFileImport: IconType
external val FaFileInvoiceDollar: IconType
external val FaFileInvoice: IconType
external val FaFileMedicalAlt: IconType
external val FaFileMedical: IconType
external val FaFilePdf: IconType
external val FaFilePowerpoint: IconType
external val FaFilePrescription: IconType
external val FaFileSignature: IconType
external val FaFileUpload: IconType
external val FaFileVideo: IconType
external val FaFileWord: IconType
external val FaFile: IconType
external val FaFillDrip: IconType
external val FaFill: IconType
external val FaFilm: IconType
external val FaFilter: IconType
external val FaFingerprint: IconType
external val FaFireAlt: IconType
external val FaFireExtinguisher: IconType
external val FaFire: IconType
external val FaFirstAid: IconType
external val FaFish: IconType
external val FaFistRaised: IconType
external val FaFlagCheckered: IconType
external val FaFlagUsa: IconType
external val FaFlag: IconType
external val FaFlask: IconType
external val FaFlushed: IconType
external val FaFolderMinus: IconType
external val FaFolderOpen: IconType
external val FaFolderPlus: IconType
external val FaFolder: IconType
external val FaFont: IconType
external val FaFootballBall: IconType
external val FaForward: IconType
external val FaFrog: IconType
external val FaFrownOpen: IconType
external val FaFrown: IconType
external val FaFunnelDollar: IconType
external val FaFutbol: IconType
external val FaGamepad: IconType
external val FaGasPump: IconType
external val FaGavel: IconType
external val FaGem: IconType
external val FaGenderless: IconType
external val FaGhost: IconType
external val FaGift: IconType
external val FaGifts: IconType
external val FaGlassCheers: IconType
external val FaGlassMartiniAlt: IconType
external val FaGlassMartini: IconType
external val FaGlassWhiskey: IconType
external val FaGlasses: IconType
external val FaGlobeAfrica: IconType
external val FaGlobeAmericas: IconType
external val FaGlobeAsia: IconType
external val FaGlobeEurope: IconType
external val FaGlobe: IconType
external val FaGolfBall: IconType
external val FaGopuram: IconType
external val FaGraduationCap: IconType
external val FaGreaterThanEqual: IconType
external val FaGreaterThan: IconType
external val FaGrimace: IconType
external val FaGrinAlt: IconType
external val FaGrinBeamSweat: IconType
external val FaGrinBeam: IconType
external val FaGrinHearts: IconType
external val FaGrinSquintTears: IconType
external val FaGrinSquint: IconType
external val FaGrinStars: IconType
external val FaGrinTears: IconType
external val FaGrinTongueSquint: IconType
external val FaGrinTongueWink: IconType
external val FaGrinTongue: IconType
external val FaGrinWink: IconType
external val FaGrin: IconType
external val FaGripHorizontal: IconType
external val FaGripLinesVertical: IconType
external val FaGripLines: IconType
external val FaGripVertical: IconType
external val FaGuitar: IconType
external val FaHSquare: IconType
external val FaHamburger: IconType
external val FaHammer: IconType
external val FaHamsa: IconType
external val FaHandHoldingHeart: IconType
external val FaHandHoldingMedical: IconType
external val FaHandHoldingUsd: IconType
external val FaHandHoldingWater: IconType
external val FaHandHolding: IconType
external val FaHandLizard: IconType
external val FaHandMiddleFinger: IconType
external val FaHandPaper: IconType
external val FaHandPeace: IconType
external val FaHandPointDown: IconType
external val FaHandPointLeft: IconType
external val FaHandPointRight: IconType
external val FaHandPointUp: IconType
external val FaHandPointer: IconType
external val FaHandRock: IconType
external val FaHandScissors: IconType
external val FaHandSparkles: IconType
external val FaHandSpock: IconType
external val FaHandsHelping: IconType
external val FaHandsWash: IconType
external val FaHands: IconType
external val FaHandshakeAltSlash: IconType
external val FaHandshakeSlash: IconType
external val FaHandshake: IconType
external val FaHanukiah: IconType
external val FaHardHat: IconType
external val FaHashtag: IconType
external val FaHatCowboySide: IconType
external val FaHatCowboy: IconType
external val FaHatWizard: IconType
external val FaHdd: IconType
external val FaHeadSideCoughSlash: IconType
external val FaHeadSideCough: IconType
external val FaHeadSideMask: IconType
external val FaHeadSideVirus: IconType
external val FaHeading: IconType
external val FaHeadphonesAlt: IconType
external val FaHeadphones: IconType
external val FaHeadset: IconType
external val FaHeartBroken: IconType
external val FaHeart: IconType
external val FaHeartbeat: IconType
external val FaHelicopter: IconType
external val FaHighlighter: IconType
external val FaHiking: IconType
external val FaHippo: IconType
external val FaHistory: IconType
external val FaHockeyPuck: IconType
external val FaHollyBerry: IconType
external val FaHome: IconType
external val FaHorseHead: IconType
external val FaHorse: IconType
external val FaHospitalAlt: IconType
external val FaHospitalSymbol: IconType
external val FaHospitalUser: IconType
external val FaHospital: IconType
external val FaHotTub: IconType
external val FaHotdog: IconType
external val FaHotel: IconType
external val FaHourglassEnd: IconType
external val FaHourglassHalf: IconType
external val FaHourglassStart: IconType
external val FaHourglass: IconType
external val FaHouseDamage: IconType
external val FaHouseUser: IconType
external val FaHryvnia: IconType
external val FaICursor: IconType
external val FaIceCream: IconType
external val FaIcicles: IconType
external val FaIcons: IconType
external val FaIdBadge: IconType
external val FaIdCardAlt: IconType
external val FaIdCard: IconType
external val FaIgloo: IconType
external val FaImage: IconType
external val FaImages: IconType
external val FaInbox: IconType
external val FaIndent: IconType
external val FaIndustry: IconType
external val FaInfinity: IconType
external val FaInfoCircle: IconType
external val FaInfo: IconType
external val FaItalic: IconType
external val FaJedi: IconType
external val FaJoint: IconType
external val FaJournalWhills: IconType
external val FaKaaba: IconType
external val FaKey: IconType
external val FaKeyboard: IconType
external val FaKhanda: IconType
external val FaKissBeam: IconType
external val FaKissWinkHeart: IconType
external val FaKiss: IconType
external val FaKiwiBird: IconType
external val FaLandmark: IconType
external val FaLanguage: IconType
external val FaLaptopCode: IconType
external val FaLaptopHouse: IconType
external val FaLaptopMedical: IconType
external val FaLaptop: IconType
external val FaLaughBeam: IconType
external val FaLaughSquint: IconType
external val FaLaughWink: IconType
external val FaLaugh: IconType
external val FaLayerGroup: IconType
external val FaLeaf: IconType
external val FaLemon: IconType
external val FaLessThanEqual: IconType
external val FaLessThan: IconType
external val FaLevelDownAlt: IconType
external val FaLevelUpAlt: IconType
external val FaLifeRing: IconType
external val FaLightbulb: IconType
external val FaLink: IconType
external val FaLiraSign: IconType
external val FaListAlt: IconType
external val FaListOl: IconType
external val FaListUl: IconType
external val FaList: IconType
external val FaLocationArrow: IconType
external val FaLockOpen: IconType
external val FaLock: IconType
external val FaLongArrowAltDown: IconType
external val FaLongArrowAltLeft: IconType
external val FaLongArrowAltRight: IconType
external val FaLongArrowAltUp: IconType
external val FaLowVision: IconType
external val FaLuggageCart: IconType
external val FaLungsVirus: IconType
external val FaLungs: IconType
external val FaMagic: IconType
external val FaMagnet: IconType
external val FaMailBulk: IconType
external val FaMale: IconType
external val FaMapMarkedAlt: IconType
external val FaMapMarked: IconType
external val FaMapMarkerAlt: IconType
external val FaMapMarker: IconType
external val FaMapPin: IconType
external val FaMapSigns: IconType
external val FaMap: IconType
external val FaMarker: IconType
external val FaMarsDouble: IconType
external val FaMarsStrokeH: IconType
external val FaMarsStrokeV: IconType
external val FaMarsStroke: IconType
external val FaMars: IconType
external val FaMask: IconType
external val FaMedal: IconType
external val FaMedkit: IconType
external val FaMehBlank: IconType
external val FaMehRollingEyes: IconType
external val FaMeh: IconType
external val FaMemory: IconType
external val FaMenorah: IconType
external val FaMercury: IconType
external val FaMeteor: IconType
external val FaMicrochip: IconType
external val FaMicrophoneAltSlash: IconType
external val FaMicrophoneAlt: IconType
external val FaMicrophoneSlash: IconType
external val FaMicrophone: IconType
external val FaMicroscope: IconType
external val FaMinusCircle: IconType
external val FaMinusSquare: IconType
external val FaMinus: IconType
external val FaMitten: IconType
external val FaMobileAlt: IconType
external val FaMobile: IconType
external val FaMoneyBillAlt: IconType
external val FaMoneyBillWaveAlt: IconType
external val FaMoneyBillWave: IconType
external val FaMoneyBill: IconType
external val FaMoneyCheckAlt: IconType
external val FaMoneyCheck: IconType
external val FaMonument: IconType
external val FaMoon: IconType
external val FaMortarPestle: IconType
external val FaMosque: IconType
external val FaMotorcycle: IconType
external val FaMountain: IconType
external val FaMousePointer: IconType
external val FaMouse: IconType
external val FaMugHot: IconType
external val FaMusic: IconType
external val FaNetworkWired: IconType
external val FaNeuter: IconType
external val FaNewspaper: IconType
external val FaNotEqual: IconType
external val FaNotesMedical: IconType
external val FaObjectGroup: IconType
external val FaObjectUngroup: IconType
external val FaOilCan: IconType
external val FaOm: IconType
external val FaOtter: IconType
external val FaOutdent: IconType
external val FaPager: IconType
external val FaPaintBrush: IconType
external val FaPaintRoller: IconType
external val FaPalette: IconType
external val FaPallet: IconType
external val FaPaperPlane: IconType
external val FaPaperclip: IconType
external val FaParachuteBox: IconType
external val FaParagraph: IconType
external val FaParking: IconType
external val FaPassport: IconType
external val FaPastafarianism: IconType
external val FaPaste: IconType
external val FaPauseCircle: IconType
external val FaPause: IconType
external val FaPaw: IconType
external val FaPeace: IconType
external val FaPenAlt: IconType
external val FaPenFancy: IconType
external val FaPenNib: IconType
external val FaPenSquare: IconType
external val FaPen: IconType
external val FaPencilAlt: IconType
external val FaPencilRuler: IconType
external val FaPeopleArrows: IconType
external val FaPeopleCarry: IconType
external val FaPepperHot: IconType
external val FaPercent: IconType
external val FaPercentage: IconType
external val FaPersonBooth: IconType
external val FaPhoneAlt: IconType
external val FaPhoneSlash: IconType
external val FaPhoneSquareAlt: IconType
external val FaPhoneSquare: IconType
external val FaPhoneVolume: IconType
external val FaPhone: IconType
external val FaPhotoVideo: IconType
external val FaPiggyBank: IconType
external val FaPills: IconType
external val FaPizzaSlice: IconType
external val FaPlaceOfWorship: IconType
external val FaPlaneArrival: IconType
external val FaPlaneDeparture: IconType
external val FaPlaneSlash: IconType
external val FaPlane: IconType
external val FaPlayCircle: IconType
external val FaPlay: IconType
external val FaPlug: IconType
external val FaPlusCircle: IconType
external val FaPlusSquare: IconType
external val FaPlus: IconType
external val FaPodcast: IconType
external val FaPollH: IconType
external val FaPoll: IconType
external val FaPooStorm: IconType
external val FaPoo: IconType
external val FaPoop: IconType
external val FaPortrait: IconType
external val FaPoundSign: IconType
external val FaPowerOff: IconType
external val FaPray: IconType
external val FaPrayingHands: IconType
external val FaPrescriptionBottleAlt: IconType
external val FaPrescriptionBottle: IconType
external val FaPrescription: IconType
external val FaPrint: IconType
external val FaProcedures: IconType
external val FaProjectDiagram: IconType
external val FaPumpMedical: IconType
external val FaPumpSoap: IconType
external val FaPuzzlePiece: IconType
external val FaQrcode: IconType
external val FaQuestionCircle: IconType
external val FaQuestion: IconType
external val FaQuidditch: IconType
external val FaQuoteLeft: IconType
external val FaQuoteRight: IconType
external val FaQuran: IconType
external val FaRadiationAlt: IconType
external val FaRadiation: IconType
external val FaRainbow: IconType
external val FaRandom: IconType
external val FaReceipt: IconType
external val FaRecordVinyl: IconType
external val FaRecycle: IconType
external val FaRedoAlt: IconType
external val FaRedo: IconType
external val FaRegistered: IconType
external val FaRemoveFormat: IconType
external val FaReplyAll: IconType
external val FaReply: IconType
external val FaRepublican: IconType
external val FaRestroom: IconType
external val FaRetweet: IconType
external val FaRibbon: IconType
external val FaRing: IconType
external val FaRoad: IconType
external val FaRobot: IconType
external val FaRocket: IconType
external val FaRoute: IconType
external val FaRssSquare: IconType
external val FaRss: IconType
external val FaRubleSign: IconType
external val FaRulerCombined: IconType
external val FaRulerHorizontal: IconType
external val FaRulerVertical: IconType
external val FaRuler: IconType
external val FaRunning: IconType
external val FaRupeeSign: IconType
external val FaSadCry: IconType
external val FaSadTear: IconType
external val FaSatelliteDish: IconType
external val FaSatellite: IconType
external val FaSave: IconType
external val FaSchool: IconType
external val FaScrewdriver: IconType
external val FaScroll: IconType
external val FaSdCard: IconType
external val FaSearchDollar: IconType
external val FaSearchLocation: IconType
external val FaSearchMinus: IconType
external val FaSearchPlus: IconType
external val FaSearch: IconType
external val FaSeedling: IconType
external val FaServer: IconType
external val FaShapes: IconType
external val FaShareAltSquare: IconType
external val FaShareAlt: IconType
external val FaShareSquare: IconType
external val FaShare: IconType
external val FaShekelSign: IconType
external val FaShieldAlt: IconType
external val FaShieldVirus: IconType
external val FaShip: IconType
external val FaShippingFast: IconType
external val FaShoePrints: IconType
external val FaShoppingBag: IconType
external val FaShoppingBasket: IconType
external val FaShoppingCart: IconType
external val FaShower: IconType
external val FaShuttleVan: IconType
external val FaSignInAlt: IconType
external val FaSignLanguage: IconType
external val FaSignOutAlt: IconType
external val FaSign: IconType
external val FaSignal: IconType
external val FaSignature: IconType
external val FaSimCard: IconType
external val FaSink: IconType
external val FaSitemap: IconType
external val FaSkating: IconType
external val FaSkiingNordic: IconType
external val FaSkiing: IconType
external val FaSkullCrossbones: IconType
external val FaSkull: IconType
external val FaSlash: IconType
external val FaSleigh: IconType
external val FaSlidersH: IconType
external val FaSmileBeam: IconType
external val FaSmileWink: IconType
external val FaSmile: IconType
external val FaSmog: IconType
external val FaSmokingBan: IconType
external val FaSmoking: IconType
external val FaSms: IconType
external val FaSnowboarding: IconType
external val FaSnowflake: IconType
external val FaSnowman: IconType
external val FaSnowplow: IconType
external val FaSoap: IconType
external val FaSocks: IconType
external val FaSolarPanel: IconType
external val FaSortAlphaDownAlt: IconType
external val FaSortAlphaDown: IconType
external val FaSortAlphaUpAlt: IconType
external val FaSortAlphaUp: IconType
external val FaSortAmountDownAlt: IconType
external val FaSortAmountDown: IconType
external val FaSortAmountUpAlt: IconType
external val FaSortAmountUp: IconType
external val FaSortDown: IconType
external val FaSortNumericDownAlt: IconType
external val FaSortNumericDown: IconType
external val FaSortNumericUpAlt: IconType
external val FaSortNumericUp: IconType
external val FaSortUp: IconType
external val FaSort: IconType
external val FaSpa: IconType
external val FaSpaceShuttle: IconType
external val FaSpellCheck: IconType
external val FaSpider: IconType
external val FaSpinner: IconType
external val FaSplotch: IconType
external val FaSprayCan: IconType
external val FaSquareFull: IconType
external val FaSquareRootAlt: IconType
external val FaSquare: IconType
external val FaStamp: IconType
external val FaStarAndCrescent: IconType
external val FaStarHalfAlt: IconType
external val FaStarHalf: IconType
external val FaStarOfDavid: IconType
external val FaStarOfLife: IconType
external val FaStar: IconType
external val FaStepBackward: IconType
external val FaStepForward: IconType
external val FaStethoscope: IconType
external val FaStickyNote: IconType
external val FaStopCircle: IconType
external val FaStop: IconType
external val FaStopwatch20: IconType
external val FaStopwatch: IconType
external val FaStoreAltSlash: IconType
external val FaStoreAlt: IconType
external val FaStoreSlash: IconType
external val FaStore: IconType
external val FaStream: IconType
external val FaStreetView: IconType
external val FaStrikethrough: IconType
external val FaStroopwafel: IconType
external val FaSubscript: IconType
external val FaSubway: IconType
external val FaSuitcaseRolling: IconType
external val FaSuitcase: IconType
external val FaSun: IconType
external val FaSuperscript: IconType
external val FaSurprise: IconType
external val FaSwatchbook: IconType
external val FaSwimmer: IconType
external val FaSwimmingPool: IconType
external val FaSynagogue: IconType
external val FaSyncAlt: IconType
external val FaSync: IconType
external val FaSyringe: IconType
external val FaTableTennis: IconType
external val FaTable: IconType
external val FaTabletAlt: IconType
external val FaTablet: IconType
external val FaTablets: IconType
external val FaTachometerAlt: IconType
external val FaTag: IconType
external val FaTags: IconType
external val FaTape: IconType
external val FaTasks: IconType
external val FaTaxi: IconType
external val FaTeethOpen: IconType
external val FaTeeth: IconType
external val FaTemperatureHigh: IconType
external val FaTemperatureLow: IconType
external val FaTenge: IconType
external val FaTerminal: IconType
external val FaTextHeight: IconType
external val FaTextWidth: IconType
external val FaThLarge: IconType
external val FaThList: IconType
external val FaTh: IconType
external val FaTheaterMasks: IconType
external val FaThermometerEmpty: IconType
external val FaThermometerFull: IconType
external val FaThermometerHalf: IconType
external val FaThermometerQuarter: IconType
external val FaThermometerThreeQuarters: IconType
external val FaThermometer: IconType
external val FaThumbsDown: IconType
external val FaThumbsUp: IconType
external val FaThumbtack: IconType
external val FaTicketAlt: IconType
external val FaTimesCircle: IconType
external val FaTimes: IconType
external val FaTintSlash: IconType
external val FaTint: IconType
external val FaTired: IconType
external val FaToggleOff: IconType
external val FaToggleOn: IconType
external val FaToiletPaperSlash: IconType
external val FaToiletPaper: IconType
external val FaToilet: IconType
external val FaToolbox: IconType
external val FaTools: IconType
external val FaTooth: IconType
external val FaTorah: IconType
external val FaToriiGate: IconType
external val FaTractor: IconType
external val FaTrademark: IconType
external val FaTrafficLight: IconType
external val FaTrailer: IconType
external val FaTrain: IconType
external val FaTram: IconType
external val FaTransgenderAlt: IconType
external val FaTransgender: IconType
external val FaTrashAlt: IconType
external val FaTrashRestoreAlt: IconType
external val FaTrashRestore: IconType
external val FaTrash: IconType
external val FaTree: IconType
external val FaTrophy: IconType
external val FaTruckLoading: IconType
external val FaTruckMonster: IconType
external val FaTruckMoving: IconType
external val FaTruckPickup: IconType
external val FaTruck: IconType
external val FaTshirt: IconType
external val FaTty: IconType
external val FaTv: IconType
external val FaUmbrellaBeach: IconType
external val FaUmbrella: IconType
external val FaUnderline: IconType
external val FaUndoAlt: IconType
external val FaUndo: IconType
external val FaUniversalAccess: IconType
external val FaUniversity: IconType
external val FaUnlink: IconType
external val FaUnlockAlt: IconType
external val FaUnlock: IconType
external val FaUpload: IconType
external val FaUserAltSlash: IconType
external val FaUserAlt: IconType
external val FaUserAstronaut: IconType
external val FaUserCheck: IconType
external val FaUserCircle: IconType
external val FaUserClock: IconType
external val FaUserCog: IconType
external val FaUserEdit: IconType
external val FaUserFriends: IconType
external val FaUserGraduate: IconType
external val FaUserInjured: IconType
external val FaUserLock: IconType
external val FaUserMd: IconType
external val FaUserMinus: IconType
external val FaUserNinja: IconType
external val FaUserNurse: IconType
external val FaUserPlus: IconType
external val FaUserSecret: IconType
external val FaUserShield: IconType
external val FaUserSlash: IconType
external val FaUserTag: IconType
external val FaUserTie: IconType
external val FaUserTimes: IconType
external val FaUser: IconType
external val FaUsersCog: IconType
external val FaUsersSlash: IconType
external val FaUsers: IconType
external val FaUtensilSpoon: IconType
external val FaUtensils: IconType
external val FaVectorSquare: IconType
external val FaVenusDouble: IconType
external val FaVenusMars: IconType
external val FaVenus: IconType
external val FaVestPatches: IconType
external val FaVest: IconType
external val FaVial: IconType
external val FaVials: IconType
external val FaVideoSlash: IconType
external val FaVideo: IconType
external val FaVihara: IconType
external val FaVirusSlash: IconType
external val FaVirus: IconType
external val FaViruses: IconType
external val FaVoicemail: IconType
external val FaVolleyballBall: IconType
external val FaVolumeDown: IconType
external val FaVolumeMute: IconType
external val FaVolumeOff: IconType
external val FaVolumeUp: IconType
external val FaVoteYea: IconType
external val FaVrCardboard: IconType
external val FaWalking: IconType
external val FaWallet: IconType
external val FaWarehouse: IconType
external val FaWater: IconType
external val FaWaveSquare: IconType
external val FaWeightHanging: IconType
external val FaWeight: IconType
external val FaWheelchair: IconType
external val FaWifi: IconType
external val FaWind: IconType
external val FaWindowClose: IconType
external val FaWindowMaximize: IconType
external val FaWindowMinimize: IconType
external val FaWindowRestore: IconType
external val FaWineBottle: IconType
external val FaWineGlassAlt: IconType
external val FaWineGlass: IconType
external val FaWonSign: IconType
external val FaWrench: IconType
external val FaXRay: IconType
external val FaYenSign: IconType
external val FaYinYang: IconType
external val FaRegAddressBook: IconType
external val FaRegAddressCard: IconType
external val FaRegAngry: IconType
external val FaRegArrowAltCircleDown: IconType
external val FaRegArrowAltCircleLeft: IconType
external val FaRegArrowAltCircleRight: IconType
external val FaRegArrowAltCircleUp: IconType
external val FaRegBellSlash: IconType
external val FaRegBell: IconType
external val FaRegBookmark: IconType
external val FaRegBuilding: IconType
external val FaRegCalendarAlt: IconType
external val FaRegCalendarCheck: IconType
external val FaRegCalendarMinus: IconType
external val FaRegCalendarPlus: IconType
external val FaRegCalendarTimes: IconType
external val FaRegCalendar: IconType
external val FaRegCaretSquareDown: IconType
external val FaRegCaretSquareLeft: IconType
external val FaRegCaretSquareRight: IconType
external val FaRegCaretSquareUp: IconType
external val FaRegChartBar: IconType
external val FaRegCheckCircle: IconType
external val FaRegCheckSquare: IconType
external val FaRegCircle: IconType
external val FaRegClipboard: IconType
external val FaRegClock: IconType
external val FaRegClone: IconType
external val FaRegClosedCaptioning: IconType
external val FaRegCommentAlt: IconType
external val FaRegCommentDots: IconType
external val FaRegComment: IconType
external val FaRegComments: IconType
external val FaRegCompass: IconType
external val FaRegCopy: IconType
external val FaRegCopyright: IconType
external val FaRegCreditCard: IconType
external val FaRegDizzy: IconType
external val FaRegDotCircle: IconType
external val FaRegEdit: IconType
external val FaRegEnvelopeOpen: IconType
external val FaRegEnvelope: IconType
external val FaRegEyeSlash: IconType
external val FaRegEye: IconType
external val FaRegFileAlt: IconType
external val FaRegFileArchive: IconType
external val FaRegFileAudio: IconType
external val FaRegFileCode: IconType
external val FaRegFileExcel: IconType
external val FaRegFileImage: IconType
external val FaRegFilePdf: IconType
external val FaRegFilePowerpoint: IconType
external val FaRegFileVideo: IconType
external val FaRegFileWord: IconType
external val FaRegFile: IconType
external val FaRegFlag: IconType
external val FaRegFlushed: IconType
external val FaRegFolderOpen: IconType
external val FaRegFolder: IconType
external val FaRegFontAwesomeLogoFull: IconType
external val FaRegFrownOpen: IconType
external val FaRegFrown: IconType
external val FaRegFutbol: IconType
external val FaRegGem: IconType
external val FaRegGrimace: IconType
external val FaRegGrinAlt: IconType
external val FaRegGrinBeamSweat: IconType
external val FaRegGrinBeam: IconType
external val FaRegGrinHearts: IconType
external val FaRegGrinSquintTears: IconType
external val FaRegGrinSquint: IconType
external val FaRegGrinStars: IconType
external val FaRegGrinTears: IconType
external val FaRegGrinTongueSquint: IconType
external val FaRegGrinTongueWink: IconType
external val FaRegGrinTongue: IconType
external val FaRegGrinWink: IconType
external val FaRegGrin: IconType
external val FaRegHandLizard: IconType
external val FaRegHandPaper: IconType
external val FaRegHandPeace: IconType
external val FaRegHandPointDown: IconType
external val FaRegHandPointLeft: IconType
external val FaRegHandPointRight: IconType
external val FaRegHandPointUp: IconType
external val FaRegHandPointer: IconType
external val FaRegHandRock: IconType
external val FaRegHandScissors: IconType
external val FaRegHandSpock: IconType
external val FaRegHandshake: IconType
external val FaRegHdd: IconType
external val FaRegHeart: IconType
external val FaRegHospital: IconType
external val FaRegHourglass: IconType
external val FaRegIdBadge: IconType
external val FaRegIdCard: IconType
external val FaRegImage: IconType
external val FaRegImages: IconType
external val FaRegKeyboard: IconType
external val FaRegKissBeam: IconType
external val FaRegKissWinkHeart: IconType
external val FaRegKiss: IconType
external val FaRegLaughBeam: IconType
external val FaRegLaughSquint: IconType
external val FaRegLaughWink: IconType
external val FaRegLaugh: IconType
external val FaRegLemon: IconType
external val FaRegLifeRing: IconType
external val FaRegLightbulb: IconType
external val FaRegListAlt: IconType
external val FaRegMap: IconType
external val FaRegMehBlank: IconType
external val FaRegMehRollingEyes: IconType
external val FaRegMeh: IconType
external val FaRegMinusSquare: IconType
external val FaRegMoneyBillAlt: IconType
external val FaRegMoon: IconType
external val FaRegNewspaper: IconType
external val FaRegObjectGroup: IconType
external val FaRegObjectUngroup: IconType
external val FaRegPaperPlane: IconType
external val FaRegPauseCircle: IconType
external val FaRegPlayCircle: IconType
external val FaRegPlusSquare: IconType
external val FaRegQuestionCircle: IconType
external val FaRegRegistered: IconType
external val FaRegSadCry: IconType
external val FaRegSadTear: IconType
external val FaRegSave: IconType
external val FaRegShareSquare: IconType
external val FaRegSmileBeam: IconType
external val FaRegSmileWink: IconType
external val FaRegSmile: IconType
external val FaRegSnowflake: IconType
external val FaRegSquare: IconType
external val FaRegStarHalf: IconType
external val FaRegStar: IconType
external val FaRegStickyNote: IconType
external val FaRegStopCircle: IconType
external val FaRegSun: IconType
external val FaRegSurprise: IconType
external val FaRegThumbsDown: IconType
external val FaRegThumbsUp: IconType
external val FaRegTimesCircle: IconType
external val FaRegTired: IconType
external val FaRegTrashAlt: IconType
external val FaRegUserCircle: IconType
external val FaRegUser: IconType
external val FaRegWindowClose: IconType
external val FaRegWindowMaximize: IconType
external val FaRegWindowMinimize: IconType
external val FaRegWindowRestore: IconType
